language: generic
sudo: required

services:
    - docker
   
before_install:
    - docker build -t marco/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true marco/docker-react npm run test